rm illumina_*.tmp
rm illumina_*.stats
rm illumina_*.dup.bam
rm illumina_*.dup.bam.txt
rm illumina_*.calmd.bam.txt
rm illumina_*.bam
rm illumina_*.bam.bai
rm illumina_*.trm.fastq
rm illumina_*.lc.fastq
rm illumina_*.lc.*
rm illumina_*.ndp.fastq
rm illumina_*.lc_seqs.fq.fastq
rm illumina_*.ndp.lc.fastq
rm illumina_*.ndp.lc.trm.bam
rm illumina_*.ndp.lc.trm.fastq
rm illumina_*.ndp.lc.trm.s.bam
rm illumina_*.ndp.lc.trm.s.bam.bai
rm illumina_*prinseq_bad*
rm -r illumina_ *fastqc_out
rm illumina_*.fastp.fastq*
rm illumina_*.html
rm illumina_*.json
rm illumina_*.out
rm illumina_*.err

rm promethion_*.tmp
rm promethion_*.stats
rm promethion_*.dup.bam
rm promethion_*.dup.bam.txt
rm promethion_*.calmd.bam.txt
rm promethion_*.bam
rm promethion_*.bam.bai
rm promethion_*.trm.fastq
rm promethion_*.lc.fastq
rm promethion_*.lc.*
rm promethion_*.ndp.fastq
rm promethion_*.lc_seqs.fq.fastq
rm promethion_*.ndp.lc.fastq
rm promethion_*.ndp.lc.trm.bam
rm promethion_*.ndp.lc.trm.fastq
rm promethion_*.ndp.lc.trm.s.bam
rm promethion_*.ndp.lc.trm.s.bam.bai
rm promethion_*prinseq_bad*
rm -r promethion_ *fastqc_out
rm promethion_*.fastp.fastq*
rm promethion_*.html
rm promethion_*.json
rm promethion_*.out
rm promethion_*.err

rm slurm-?????.out
rm fastp.json
rmdir tmp
rm *.zip
rm *.html
